version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly

    # Group all dependabot version update PRs into one
    groups:
      GitHub Actions:
        applies-to: version-updates
        patterns:
          - "*"
